spring:
  application:
    name: controle-compras-backend
  cloud:
    openfeign:
      lazy-attributes-resolution: true
  datasource:
    # protocolo://host:port/recurso
    url: jdbc:postgresql://localhost:5432/controle_compras_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.jdbc.time_zone: America/Sao_Paulo
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health

api:
  openfood:
    url: https://world.openfoodfacts.org/api/v2

